/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.turing;


import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import logica.Cinta;
import logica.Nodo;

/**
 *
 * @author david padilla
 */
public class VentanaCalculadora extends javax.swing.JFrame {
    Cinta c = new Cinta ();
    DefaultTableModel tabla1;
    String t;
    String[] vec = new String[1];
    int f;
    
    public VentanaCalculadora() {
        initComponents();
        this.setResizable(false); //Deshabilita la opción de maximizar la ventana.
        this.setLocationRelativeTo(null); //Centra la ventana
        tabla1 = new DefaultTableModel();
        this.tabla.setModel(tabla1);
        tabla1.addColumn("Máquina de Turing");
        this.f = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        var1 = new javax.swing.JTextField();
        operacion = new javax.swing.JComboBox<>();
        var2 = new javax.swing.JTextField();
        igual = new javax.swing.JButton();
        respuesta = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        panelS = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULADORA DE TURING - AUTÓMATAS");

        var1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        var1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                var1KeyTyped(evt);
            }
        });

        operacion.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        operacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/" }));

        var2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        var2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var2ActionPerformed(evt);
            }
        });
        var2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                var2KeyTyped(evt);
            }
        });

        igual.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        respuesta.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        respuesta.setText("RRR");

        reset.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null}
            },
            new String [] {
                "Máquina de Turing"
            }
        ));
        panelS.setViewportView(tabla);

        consola.setEditable(false);
        consola.setBackground(new java.awt.Color(0, 0, 0));
        consola.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        consola.setText("prueba");
        jScrollPane1.setViewportView(consola);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(var1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(var2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelS, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(var1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelS, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void var1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_var1KeyTyped
        char caracter = evt.getKeyChar();
      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_var1KeyTyped

    private void var2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_var2KeyTyped
        char caracter = evt.getKeyChar();
      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_var2KeyTyped

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        JOptionPane.showMessageDialog(this, "profe ponganos 5, gracias :)");

        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        var1.setText("");
        var2.setText("");
        respuesta.setText("RRR");
        consola.setText("");
        operacion.setSelectedIndex(0);
        tabla1 = new DefaultTableModel();
        this.tabla.setModel(tabla1);
        tabla1.addColumn("Máquina de Turing");
        c = new Cinta ();
        f = 0;
        t = "";
        igual.setEnabled(true);
    }//GEN-LAST:event_resetActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        
        if(var2.getText().equals("0")){
            JOptionPane.showMessageDialog(this, "no se puede dividir entre Cero");
        }
        else{
        if (var1.getText().equals("") || var2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Rellene los campos vacíos", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            igual.setEnabled(false);
            String op = operacion.getSelectedItem().toString();
            char caracter = op.charAt(0);
            c = c.llenarCinta(Integer.parseInt(var1.getText()), Integer.parseInt(var2.getText()), caracter);
            t = ">INICIANDO OPERACION: "+Integer.parseInt(var1.getText())+" "+caracter+" "
                    +Integer.parseInt(var2.getText())+"\n>Llenando cinta...\n>Resultado: "+cinta();
            vec[0] = cinta();
            tabla1.addRow(vec);
            consola.setText(t);
            switch(op){
                case "+": 
                    suma ();
                    break;
                case "-": 
                    resta ();
                    break;
                case "*": 
                    multiplicacion();
                    break;
                case "/": 
                    division ();
                    break;
            }
        }
        }
    }//GEN-LAST:event_igualActionPerformed

    private void var2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var2ActionPerformed
          
    }//GEN-LAST:event_var2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }
    
    private String cinta (){
        Nodo aux = c.getPrimero();
        String cad = "#";
        while (aux != null){
            cad += aux.getDato();
            aux = aux.getSig();
        }
        return cad+"#";
    }
    
    private void suma (){
        Nodo aux = c.getPrimero();
        t += "\n>Partiendo #[0] → ";
        int sum = 0;
        f++;
        while (true){
            if (aux.getDato() == '1'){
                aux.setDato('x');
                aux = aux.getSig();
                t += "\n>1["+f+"] {1:X} → ";
                vec[0] = cinta();
                tabla1.addRow(vec);
                f++;
                boolean b = true;
                while (true){
                    if (aux == null && b == true){
                        c.insertarFinal('=');
                        t += "\n>#["+f+"] {#:=} → ";
                        vec[0] = cinta();
                        tabla1.addRow(vec);
                        f++;
                        c.insertarFinal('1');
                        t += "\n>#["+f+"] {#:1} ← ";
                        vec[0] = cinta();
                        tabla1.addRow(vec);
                        f--;
                        aux = c.devolverUltimo();
                        aux = aux.getAnt();
                        break;
                    }else if (aux == null && b == false){
                        c.insertarFinal('1');
                        t += "\n>#["+f+"] {#:1} ← ";
                        vec[0] = cinta();
                        tabla1.addRow(vec);
                        f--;
                        aux = c.devolverUltimo();
                        aux = aux.getAnt();
                        break;
                    }else if (aux.getDato() == '1' || aux.getDato() == '+'){
                        t += "\n>"+aux.getDato()+"["+f+"] → ";
                        aux = aux.getSig();
                        f++;
                    }else if(aux.getDato() == '='){
                        t += "\n>"+aux.getDato()+"["+f+"] → ";
                        aux = aux.getSig();
                        f++;
                        b = false;
                    }
                }
                
                while (true){
                    if (aux.getDato() == '1' || aux.getDato() == '=' || aux.getDato() == '+'){
                        t += "\n>"+aux.getDato()+"["+f+"] ← ";
                        f--;
                        aux = aux.getAnt();
                    }else if (aux.getDato() == 'x'){
                        t += "\n>"+aux.getDato()+"["+f+"] → ";
                        f++;
                        aux = aux.getSig();
                        break;
                    }
                }
                
            }else if (aux.getDato() == '+'){
                t += "\n>"+aux.getDato()+"["+f+"] → ";
                f++;
                if (aux.getAnt() == null && aux.getSig() == null){
                    t += "\n>#["+f+"] {#:=} _ ";
                    c.insertarFinal('=');
                    aux = c.devolverUltimo();
                    vec[0] = cinta();
                    tabla1.addRow(vec);
                    break;
                }
                aux = aux.getSig();
            }else if (aux.getDato() == '='){
                t += "\n>"+aux.getDato()+"["+f+"] _\n>Operación realizada!\n>Resultado: "+cinta()+"\n>Contando 1's...";
                f++;
                break;
            }            
        }
        while (aux.getSig() != null){
           aux = aux.getSig();
           sum++;
        }
        t += "\n>FIN OPERACION: "+Integer.parseInt(var1.getText())+" + "
                    +Integer.parseInt(var2.getText())+" = "+sum;
        consola.setText(t);
        respuesta.setText(Integer.toString(sum));
    }
    
    private void resta (){
        Nodo aux = c.getPrimero();
        t += "\n>Partiendo #[0] → ";
        int rest = 0;
        f++;
        while (true){
            if (aux == null){
                c.insertarFinal('=');
                t += "\n>#["+f+"] {#:=} _ ";
                vec[0] = cinta();
                tabla1.addRow(vec);
                break;
            }else if (aux.getDato() == '1'){
                aux.setDato('x');
                aux = aux.getSig();
                t += "\n>1["+f+"] {1:X} → ";
                vec[0] = cinta();
                tabla1.addRow(vec);
                f++; 
                while (true){
                    if (aux.getDato() == '1'){
                        t += "\n>1["+f+"] → ";
                        aux = aux.getSig();
                        f++;
                    }else if (aux.getDato() == '-'){
                       t += "\n>-["+f+"] → ";
                       aux = aux.getSig();
                       f++;
                       break; 
                    }
                }
                boolean b = true;
                while (true){
                    if (aux == null && b){
                        c.insertarFinal('=');
                        t += "\n>#["+f+"] {#:=} → ";
                        vec[0] = cinta();
                        tabla1.addRow(vec);
                        f++;
                        c.insertarFinal('1');
                        t += "\n>#["+f+"] {#:1} ← ";
                        vec[0] = cinta();
                        tabla1.addRow(vec);
                        f--;
                        aux = c.devolverUltimo();
                        aux = aux.getAnt();
                        break;
                    }else if (aux == null && b == false){
                        c.insertarFinal('1');
                        t += "\n>#["+f+"] {#:1} ← ";
                        vec[0] = cinta();
                        tabla1.addRow(vec);
                        f--;
                        aux = c.devolverUltimo();
                        aux = aux.getAnt();
                        break;
                    }else if (aux.getDato() == 'y'){
                        t += "\n>Y["+f+"] → ";
                        aux = aux.getSig();
                        f++;
                    }else if (aux.getDato() == '1'){
                       t += "\n>1["+f+"] {1:Y} ← ";
                       aux.setDato('y');
                       aux = aux.getAnt();
                       vec[0] = cinta();
                        tabla1.addRow(vec);
                       f--;
                       break; 
                    }else if (aux.getDato() == '='){
                        b = false;
                        //t += "\n>=["+f+"] → ";
                        c.insertarFinal('1');
                        t += "\n>#["+f+"] {#:1} ← ";
                        vec[0] = cinta();
                        tabla1.addRow(vec);
                        f--;
                        break;
                    }
                }
                while (true){
                    if (aux.getDato() == '1' || aux.getDato() == '=' || aux.getDato() == 'y' || aux.getDato() == '-'){
                         t += "\n>"+aux.getDato()+"["+f+"] ← ";
                         aux = aux.getAnt();
                         f--;
                    }else if (aux.getDato() == 'x'){
                        t += "\n>x["+f+"] → ";
                        aux = aux.getSig();
                        f++;
                        break;
                    }
                }
            }else if (aux.getDato() == '-'){
                 t += "\n>-["+f+"] → ";
                 if (aux.getSig() == null){
                     c.insertarFinal('=');
                     t += "\n>#["+f+"] {#:=} _ ";
                     vec[0] = cinta();
                     tabla1.addRow(vec);
                     aux = c.devolverUltimo();
                     break;
                 }
                 aux = aux.getSig();
                 f++;
                 //boolean b = true;
                 while (true){
                     if (aux == null){
                        c.insertarFinal('=');
                        t += "\n>#["+f+"] {#:=} ← ";
                        vec[0] = cinta();
                        tabla1.addRow(vec);
                        f--;
                        aux = c.devolverUltimo();
                        break;
                     }else if (aux.getDato() == '='){
                         t += "\n>=["+f+"] _ ";
                         break;
                     }else if (aux.getDato() == 'y'){
                         t += "\n>y["+f+"] → ";
                         aux = aux.getSig();
                         f++;
                     }else if (aux.getDato() == '1'){
                        t += "\n>1["+f+"] {1:Y} → ";
                        aux.setDato('y');
                        aux = aux.getSig();
                        vec[0] = cinta();
                        tabla1.addRow(vec);
                        f++;
                        while (true){
                            if (aux == null){
                                c.insertarFinal('=');
                                t += "\n>#["+f+"] {#:=} → ";
                                vec[0] = cinta();
                                tabla1.addRow(vec);
                                f++;
                                c.insertarFinal('-');
                                t += "\n>#["+f+"] {#:-} → ";
                                vec[0] = cinta();
                                tabla1.addRow(vec);
                                f++;
                                c.insertarFinal('1');
                                t += "\n>#["+f+"] {#:1} ← ";
                                vec[0] = cinta();
                                tabla1.addRow(vec);
                                f--;
                                aux = c.devolverUltimo();
                                aux = aux.getAnt();
                                while (true){
                                    if (aux.getDato() == '1' || aux.getDato() == '-' || aux.getDato() == '='){
                                        t += "\n>"+aux.getDato()+"["+f+"] ← ";
                                        aux = aux.getAnt();
                                        f--;
                                    }else if (aux.getDato() == 'y'){
                                        t += "\n>y["+f+"] → ";
                                        aux = aux.getSig();
                                        f++;
                                        break;
                                    }
                                }
                                break;
                            }
                            else if (aux.getDato() == '1'){
                                t += "\n>1["+f+"] → ";
                                aux = aux.getSig();
                                f++;
                            }else if (aux.getDato() == '='){
                                t += "\n>=["+f+"] → ";
                                c.insertarFinal('1');
                                vec[0] = cinta();
                                tabla1.addRow(vec);
                                f++;
                                if (aux.getAnt().getDato() == 'y'){
                                    break;
                                }
                                
                                /*while (true){
                                    if (aux == null){
                                        c.insertarFinal('1');
                                        t += "\n>#["+f+"] {#:1} ← ";
                                        vec[0] = cinta();
                                        tabla1.addRow(vec);
                                        f--;
                                        aux = c.devolverUltimo();
                                        aux = aux.getAnt();
                                        break;
                                    }else if (aux.getDato() == '1'){
                                        t += "\n>1["+f+"] → ";
                                        aux = aux.getSig();
                                        f++;
                                    }
                                }*/
                                while (true){
                                    if (aux.getDato() == '1' || aux.getDato() == '-' || aux.getDato() == '='){
                                        t += "\n>"+aux.getDato()+"["+f+"] ← ";
                                        aux = aux.getAnt();
                                        f--;
                                    }else if (aux.getDato() == 'y'){
                                         t += "\n>y["+f+"] → ";
                                        aux = aux.getSig();
                                        f++;
                                        break;
                                    }
                                }
                                break;
                            }
                        }
                     }
                 }
               break;  
            }
        }
        aux = c.devolverUltimo();
        while (true){
            if (aux.getDato() == '1'){
                aux = aux.getAnt();
                rest++;
            }else if(aux.getDato() == '-'){
                rest = rest*(-1);
                break;
            }else if (aux.getDato() == '='){
                break;
            }
        }
        t += "\n>FIN OPERACION: "+Integer.parseInt(var1.getText())+" - "
                    +Integer.parseInt(var2.getText())+" = "+rest;
        consola.setText(t);
        respuesta.setText(Integer.toString(rest));
    }
    
    private void multiplicacion (){
        Nodo aux = c.getPrimero();
        t += "\n>Partiendo #[0] → ";
        int mult = 0;
        f++;
        while (true){
            if (aux.getDato() == '1'){
                aux.setDato('x');
                aux = aux.getSig();
                t += "\n>1["+f+"] {1:X} → ";
                vec[0] = cinta();
                tabla1.addRow(vec);
                f++; 
                while (true){
                    if (aux.getDato() == '1'){
                        t += "\n>1["+f+"] → ";
                        aux = aux.getSig();
                        f++;
                    }else if (aux.getDato() == '*'){
                       t += "\n>*["+f+"] → ";
                       aux = aux.getSig();
                       f++;
                       break; 
                    }
                }
                if (aux == null){
                    c.insertarFinal('=');
                    t += "\n>#["+f+"] {#:=} _ ";
                    vec[0] = cinta();
                    tabla1.addRow(vec);
                    aux = c.devolverUltimo();
                    break;
                }
                while (true){
                    if (aux.getDato() == 'y'){
                        t += "\n>y["+f+"] → ";
                        aux = aux.getSig();
                        f++;
                    }else if (aux.getDato() == '1'){
                       t += "\n>1["+f+"] {1:Y} → ";
                       aux.setDato('y');
                       aux = aux.getSig();
                       f++;
                       
                       while (true){
                        if (aux == null){
                            c.insertarFinal('=');
                            t += "\n>#["+f+"] {#:=} → ";
                            f++;
                            vec[0] = cinta();
                            tabla1.addRow(vec);
                            c.insertarFinal('1');
                            t += "\n>#["+f+"] {#:1} ← ";
                            f--;
                            vec[0] = cinta();
                            tabla1.addRow(vec);
                            aux = c.devolverUltimo();
                            while (true){
                                if (aux.getDato() == '1' || aux.getDato() == '='){
                                    t += "\n>"+aux.getDato()+"["+f+"] ← ";
                                    aux = aux.getAnt();
                                    f--; 
                                }else if (aux.getDato() == 'y'){
                                    t += "\n>y["+f+"] → ";
                                    aux = aux.getSig();
                                    f++;
                                    break;
                                }
                            }
                            break;
                        }else if (aux.getDato() == '1'){
                            t += "\n>1["+f+"] → ";
                            aux = aux.getSig();
                            f++;
                        }else if (aux.getDato() == '='){
                            t += "\n>=["+f+"] → ";
                            aux = aux.getSig();
                            f++;
                            while (true){
                               if (aux == null){
                                    c.insertarFinal('1');
                                    t += "\n>#["+f+"] {#:1} ← ";
                                    f--;
                                    vec[0] = cinta();
                                    tabla1.addRow(vec);
                                    aux = c.devolverUltimo();
                                    aux = aux.getAnt();
                                    break;
                                }else if (aux.getDato() == '1'){
                                    t += "\n>1["+f+"] → ";
                                    aux = aux.getSig();
                                    f++; 
                                }
                            }
                            while (true){
                                if (aux.getDato() == '1' || aux.getDato() == '='){
                                    t += "\n>"+aux.getDato()+"["+f+"] ← ";
                                    aux = aux.getAnt();
                                    f--; 
                                }else if (aux.getDato() == 'y'){
                                    t += "\n>y["+f+"] → ";
                                    aux = aux.getSig();
                                    f++;
                                    break;
                                }
                            }
                            
                            break;
                        }
                       }
                    }else if (aux.getDato() == '='){
                        t += "\n>=["+f+"] ← ";
                        aux = aux.getAnt();
                        f--;
                        while (true){
                            if (aux.getDato() == 'y'){
                                t += "\n>y["+f+"] {Y:1} ← ";
                                aux.setDato('1');
                                aux = aux.getAnt();
                                vec[0] = cinta();
                                tabla1.addRow(vec);
                                f--;
                            }else if (aux.getDato() == '*'){
                                t += "\n>*["+f+"] ← ";
                                aux = aux.getAnt();
                                f--;
                                break;
                            }
                        }
                        while (true){
                            if (aux.getDato() == '1'){
                                t += "\n>1["+f+"] ← ";
                                aux = aux.getAnt();
                                f--;
                            }else if (aux.getDato() == 'x'){
                                t += "\n>X["+f+"] → ";
                                aux = aux.getSig();
                                f++;
                                break;
                            }
                        }
                        break;
                    }   
                }
            }else if (aux.getDato() == '*'){
                t += "\n>*["+f+"] _ ";
                if (aux.getAnt() == null){
                    c.insertarFinal('=');
                    vec[0] = cinta();
                    tabla1.addRow(vec);
                }
                break;
            }
        }
        aux = c.devolverUltimo();
        while (true){
            if (aux.getDato() == '1'){
                aux = aux.getAnt();
                mult++;
            }else if (aux.getDato() == '='){
                break;
            }
        }
        t += "\n>FIN OPERACION: "+Integer.parseInt(var1.getText())+" * "
                    +Integer.parseInt(var2.getText())+" = "+mult;
        consola.setText(t);
        respuesta.setText(Integer.toString(mult));
    }
    
    private void division (){
        int contador=0;
        int res = 0;
        c.insertarPrincipio('#');
        c.insertarFinal('#'); 
        
        
        Nodo aux = c.getPrimero();
        
        
        
        
        t += "\n>Partiendo #[0] → ";
        int div = 0;
        f++;
        
        while (true){
                if(aux.getSig().getDato()=='1'||aux.getSig().getDato()=='/'){
                aux = aux.getSig();    
                break;
                }
        }
        
        if(aux.getDato()=='1'){
            t += "\n>1["+f+"] → ";
            f++;
            aux =aux.getSig();        
    
            //q1
            while(aux.getDato()=='1'||aux.getDato()=='/'){
                t += "\n>"+aux.getDato()+"["+f+"] → ";
                f++;
                aux=aux.getSig();
            }

            if(aux.getDato()== '#'){
                t += "\n>#["+f+"] {#:=} ← ";
                f--;
                aux.setDato('='); 
                c.insertarFinal('#');
                //System.out.println(aux.getDato());
                //System.out.println(cinta ());
                aux= aux.getAnt();
                vec[0] = cinta();
                tabla1.addRow(vec);
            }
            //hasta aqui estoy en q2
            // y aqui hay un 1 en el auxiliar
            
            while(aux.getDato()=='1'||aux.getDato()=='/'){
                //q2 - q3
                
                while(aux.getDato()=='1'){
                        aux.setDato('x');
                        //c.insertarFinal('#');
                        t += "\n>1["+f+"] {1:X} ← ";
                        f--;
                        vec[0] = cinta();
                        tabla1.addRow(vec);
                        aux = aux.getAnt();

                        //q3
                        
                        while(aux.getDato()=='1'|| aux.getDato()=='/'){
                            t += "\n>"+aux.getDato()+"["+f+"] ← ";
                            f--;
                            aux = aux.getAnt();
                        }
                        
                        //q3 - q4
                        if(aux.getDato()=='#'||aux.getDato()=='y'){
                            t += "\n>"+aux.getDato()+"["+f+"] → ";
                            f++;
                            aux= aux.getSig();
                            
                        }
                        
///////////////////aqui estoy en q4/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                        //q4 - q9
                        
                        if(aux.getDato()=='/'){
                            
                            t += "\n>/["+f+"] → ";
                            f++;
                            aux=aux.getSig();        
                        
                            //q9
                            while(aux.getDato()=='1'){
                                t += "\n>1["+f+"] → ";
                                f++;
                                aux=aux.getSig();
                            }
                            //q9 - q10
                            if(aux.getDato()=='x'){
                                aux.setDato('1');
                                t += "\n>X["+f+"] {X:1} → ";
                                f++;
                                vec[0] = cinta();
                                tabla1.addRow(vec);
                                aux=aux.getSig();
                            }

                            //q10
                            while(aux.getDato()=='x'){
                                t += "\n>X["+f+"] → ";
                                f++;
                                aux=aux.getSig();
                            }
                            //q10 - q11
                            if(aux.getDato()=='='){
                                t += "\n>=["+f+"] → ";
                                f--;
                                aux=aux.getSig();
                            }
                            //q11
                            while(aux.getDato()=='1'){
                                t += "\n>1["+f+"] → ";
                                f++;
                                aux=aux.getSig();
                            }
                            
                            //q11 - q12
                            if(aux.getDato()=='#'){
                                aux.setDato('r');
                                t += "\n>#["+f+"] {#:r} ← ";
                                f--;
                                vec[0] = cinta();
                                tabla1.addRow(vec);
                                aux=aux.getAnt();
                                c.insertarFinal('#');
                            }
                            //q12 - q13
                            
                            
                            while(aux.getDato()=='r'||aux.getDato()=='='||aux.getDato()=='1'||aux.getDato()=='x'){


                                while(aux.getDato()=='r'||aux.getDato()=='='||aux.getDato()=='1'){

                                    aux=aux.getAnt();


                                }
                                System.out.println("LA CINTA ES: "+cinta());
                                System.out.println("la cabecera tiene 932"+ aux.getDato());


                                if(aux.getDato()=='x'){

                                    t += "\n>X["+f+"] ← ";
                                    f--;
                                    aux=aux.getAnt();

                                    while(aux.getDato()=='x'){
                                        t += "\n>X["+f+"] ← ";
                                        f--;
                                        aux=aux.getAnt();
                                    }
                                    //q13 - q16
                                    if(aux.getDato()=='1'){
                                        t += "\n>1["+f+"] → ";
                                        f++;
                                        aux=aux.getSig();
                                    }
                                    //q16 - q15
                                    if(aux.getDato()=='x'){
                                        aux.setDato('1');
                                        t += "\n>X["+f+"] {X:1} → ";
                                        f++;
                                        vec[0] = cinta();
                                        tabla1.addRow(vec);
                                        aux=aux.getSig();
                                        c.insertarFinal('#');
                                    }

                                    //q15
                                    while(aux.getDato()=='x'){
                                        t += "\n>X["+f+"] → ";
                                        f++;
                                        aux=aux.getSig();
                                    }
                                    //q15 - q14

                                    if(aux.getDato()=='='){
                                        t += "\n>=["+f+"] → ";
                                        f++;
                                        aux=aux.getSig();
                                    }
                                    //q14
                                    while(aux.getDato()=='r'||aux.getDato()=='1'){
                                        t += "\n>"+aux.getDato()+"["+f+"] → ";
                                        f++;
                                        aux=aux.getSig();
                                    }
                                    //q14 - q12
                                    if(aux.getDato()=='#'){
                                        aux.setDato('1');
                                        t += "\n>#["+f+"] {#:1} ← ";
                                        f--;
                                        vec[0] = cinta();
                                        tabla1.addRow(vec);
                                        aux=aux.getAnt();
                                    }
                                }
                            }
                            //q12 - q17
                            if(aux.getDato()=='/'){
                                t += "\n>/["+f+"] → ";
                                f++;
                                aux=aux.getSig();
                            }
                            while(aux.getDato()=='1'){
                                t += "\n>1["+f+"] → ";
                                f++;
                                aux=aux.getSig();
                            }
                            //q17 - q18
                            if(aux.getDato()=='='){
                                t += "\n>=["+f+"] → ";
                                f++;
                                aux=aux.getSig();
                                System.out.println("aqui está el resultado de 1029 : "+ cinta());
                                
                                aux = c.devolverUltimo();
                                while (aux.getDato() != '='){
                                    aux = aux.getAnt();
                                }
                                
                                aux=aux.getSig();
                                while (aux.getDato()=='1'){
                                    aux = aux.getSig();
                                    div++;
                                }
                                if(aux.getDato()=='r'){
                                    aux=aux.getSig();
                                    while(aux.getDato() == '1'){
                                        aux = aux.getSig();
                                        res++;
                                    }
                                }
                                t += "\n>FIN OPERACION: "+Integer.parseInt(var1.getText())+" / "
                                            +Integer.parseInt(var2.getText())+" = "+div+" R "+res;
                                consola.setText(t);
                                respuesta.setText(Integer.toString(div));
                                
                                contador=1;
                            }
                        }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                    //q4 - q5
                       
                    if(aux.getDato()=='1'&&contador==0){                        
                        aux.setDato('y');
                        c.insertarFinal('#');
                        t += "\n>1["+f+"] {1:y} → ";
                        f++;
                        vec[0] = cinta();
                        tabla1.addRow(vec);
                        aux=aux.getSig();
                    }
                    while(aux.getDato()=='1'||aux.getDato()=='/'){
                        t += "\n>"+aux.getDato()+"["+f+"] → ";
                        f++;
                        aux= aux.getSig();
                    }
                    if(aux.getDato()=='x'){
                        t += "\n>X["+f+"] ← ";
                        f--;    
                        aux=aux.getAnt();
                    }
                }
                while(aux.getDato()=='/'){
                    aux=aux.getSig();
                    while(aux.getDato()=='x'){
                        aux.setDato('1'); 
                        aux=aux.getSig();
                    }
                    if(aux.getDato()=='='){
                        aux= aux.getSig();
                    }
                    while(aux.getDato()=='1'){
                        aux= aux.getSig();
                    }
                    if(aux.getDato()== '#'){
                        aux.setDato('1');
                        aux = aux.getAnt();
                    }
                    while(aux.getDato()=='1'){
                        aux= aux.getAnt();
                    }
                    if(aux.getDato()=='='){
                        aux=aux.getAnt();
                    }
                }
            }
        }
        //q0 - q19

        else {
            if(aux.getDato()=='/'){
                t += "\n>/["+f+"] → ";
                f++;
                aux = aux.getSig();
                while(aux.getDato()=='1'){
                    t += "\n>1["+f+"] → ";
                    f++;
                    aux=aux.getSig();
                }
                if(aux.getDato()=='#'){
                    aux.setDato('=');
                    t += "\n>#["+f+"] {#:=} → ";
                    f++;
                    vec[0] = cinta();
                    tabla1.addRow(vec);
                    aux=aux.getSig();
                    //aqui acaba y va a l estado de aceptacion
                }
            }
            
                                aux = c.devolverUltimo();
                                System.out.println("ultimo aqui :"+aux.getDato());
                                 
                                
                                
                                
                                t += "\n>FIN OPERACION: "+Integer.parseInt(var1.getText())+" / "
                                            +Integer.parseInt(var2.getText())+" = "+div+" R "+res;
                                consola.setText(t);
                                respuesta.setText(Integer.toString(div));
                                 
        } 
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane consola;
    private javax.swing.JButton igual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> operacion;
    private javax.swing.JScrollPane panelS;
    private javax.swing.JButton reset;
    private javax.swing.JLabel respuesta;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField var1;
    private javax.swing.JTextField var2;
    // End of variables declaration//GEN-END:variables
}
